version: "2"
services:
   web:
      build: .
      volumes:
         - "./:/app"
         - "/app/node_modules" # http://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
      command: npm start
      ports:
         - "3000:3000"
      links:
         - mongo
   mongo:
      image: mongo
      ports:
         - "27017:27017"
