version: "2"
services:
   web:
      image: mrguiman/tao-form
      build: .
      volumes:
         - "./:/app"
      command: npm run dev
      ports:
         - "3000:3000"
         - "9229:9229"
      links:
         - mongo
   mongo:
      image: mongo
      ports:
         - "27017:27017"
